/**
 * ApexKit Global Types & IntelliSense
 * Auto-generated by apexkit-watch.js
 */

export interface Collections {
  "docs": {
    title: string;
    content: string;
    added_by: number;
    category: "getting started" | "integrations" | "core concepts" | "community guides" | "others";
  };
  "why_apexkit": {
    color: string;
    icon?: string;
    description: string;
    order?: number;
    title: string;
  };
  "use_cases": {
    title: string;
    icon_string?: string;
    icon: string;
    order?: number;
  };
  "news": {
    body: string;
    headline: string;
    is_featured?: boolean;
    date: string;
  };
  "roadmap": {
    headline: string;
    status?: "planned" | "in-progress" | "done";
    description: string;
    quarter?: string;
    progress?: number;
  };
  "changelog": {
    version?: string;
    release_date?: string;
    is_latest?: boolean;
    body: string;
  };
  "blog": {
    body: string;
    read_time?: string;
    author_id: number;
    headline: string;
    subheadline: string;
    tags?: Record<string, any> | any[];
    cover_image?: string;
  };
  "showcase": {
    thumbnail: string;
    title: string;
    description: string;
    author_id: number;
    url: string;
  };
  "starters": {
    install_command?: string;
    description?: string;
    framework: string;
    icon?: string;
    repo_url: string;
    icon_string?: string;
  };
  "optimizations": {
    title: string;
    tags?: Record<string, any> | any[];
    upvotes: number;
    slug: string;
    downvotes: number;
    author_id: number;
    content: string;
  };
  "tenancy_offers": {
    region: string;
    status: "available" | "full" | "waitlist";
    description: string;
    available_slots: number;
    specs: string;
    provider_id: number;
    provider_name: string;
  };
  "sandbox_requests": {
    sandbox_url?: string;
    created_by?: number;
    issue_title: string;
    sandbox_id: string;
    status: "open" | "closed";
    description?: string;
  };
  "discussions": {
    posted_by_id: number;
    description: string;
    topic: string;
  };
  "issues": {
    posted_by_id: number;
    title: string;
  };
  "hub_content": {
    title?: string;
  };
  "discussions_conversations": {
    content: string;
    author_id: number;
  };
  "issues_conversations": {
    author_id: number;
    content: string;
  };
  "profiles": {
    user_id: number;
    last_name: string;
    first_name: string;
  };
  "ecosystem_items": {
    description: string;
    tags?: Record<string, any> | any[];
    title: string;
    file: string;
    type: "script" | "i_action" | "schema" | "template" | "site";
    author_id: number;
  };
  "optimizations_conversations": {
    content: string;
    author_id: number;
  };
  "optimizations_votes": {
    type: "up" | "down";
    voter_id: number;
  };
  "careers": {
    type: string;
    department: string;
    salary?: string;
    title: string;
    description: string;
    author_id: number;
    location: string;
  };
  "jobs": {
    company: string;
    apply_url: string;
    author_id: number;
    salary: string;
    title: string;
    description: string;
    department?: string;
    type: string;
    location: string;
  };
  "tenant_registry": {
    app_name: string;
    owner_id: number;
    usage_or_description?: string;
  };
  "posts": {
    title?: string;
    content?: string;
  };
}

export type CollectionName = "docs" | "why_apexkit" | "use_cases" | "news" | "roadmap" | "changelog" | "blog" | "showcase" | "starters" | "optimizations" | "tenancy_offers" | "sandbox_requests" | "discussions" | "issues" | "hub_content" | "discussions_conversations" | "issues_conversations" | "profiles" | "ecosystem_items" | "optimizations_conversations" | "optimizations_votes" | "careers" | "jobs" | "tenant_registry" | "posts";


export type TriggerType =
  /** Triggered via HTTP GET/POST/PUT/DELETE on /api/v1/run/:name */
  | "manual"
  /** Runs before a record is inserted. Can validate or mutate data. */
  | "before_create_record"
  /** Runs after a record is inserted. Used for notifications/indexes. */
  | "after_create_record"
  /** Runs before an existing record is updated. Can validate changes. */
  | "before_update_record"
  /** Runs after a record is updated. */
  | "after_update_record"
  /** Runs before a record is deleted. Can block deletion. */
  | "before_delete_record"
  /** Runs after a record has been deleted. */
  | "after_delete_record"
  /** Intercepts list queries before they execute. */
  | "before_list_records"
  /** Filters or transforms listed records before response. */
  | "after_list_records"
  /** Runs before a single record is fetched. */
  | "before_get_record"
  /** Transforms a fetched record before response. */
  | "after_get_record"
  /** Runs before user authentication. Can verify IP/Rate limits. */
  | "before_user_login"
  /** Runs after successful user login. */
  | "after_user_login"
  /** Runs before user registration. Enforce roles or rules. */
  | "before_user_create"
  /** Runs after user registration. Trigger welcome emails. */
  | "after_user_create"
  /** Runs before a user is deleted. */
  | "before_user_delete"
  /** Runs after a user is deleted. */
  | "after_user_delete"
  /** Intercepts user list queries. */
  | "before_list_users"
  /** Transforms user list responses. */
  | "after_list_users"
  /** Validates collection schema before creation. */
  | "before_collection_create"
  /** Runs after collection creation. */
  | "after_collection_create"
  /** Runs before collection schema updates. */
  | "before_collection_update"
  /** Runs after collection schema updates. */
  | "after_collection_update"
  /** Runs before collection deletion. */
  | "before_collection_delete"
  /** Runs before a file is written to storage. */
  | "before_file_upload"
  /** Runs after file upload. Can trigger virus scan or indexing. */
  | "after_file_upload"
  /** Runs before file is deleted. */
  | "before_file_delete"
  /** Runs after file is deleted. */
  | "after_file_delete"
  /** Runs before relationship is linked. */
  | "before_relation_create"
  /** Runs after relationship is linked. */
  | "after_relation_create"
  /** Runs before relationship is removed. */
  | "before_relation_delete"
  /** Runs after relationship is removed. */
  | "after_relation_delete"
  /** Runs before a tenant database is provisioned. */
  | "before_tenant_create"
  /** Runs after tenant database is provisioned. */
  | "after_tenant_create"
  /** Intercepts all incoming HTTP requests to a tenant. */
  | "before_tenant_request"
  /** Processes tenant HTTP response metrics. */
  | "after_tenant_request"
  /** Intercepts sandbox requests. */
  | "before_sandbox_request"
  /** Processes sandbox response metrics. */
  | "after_sandbox_request"
  /** Intercepts AI Prompt Actions to inject RAG search vectors. */
  | "before_ai_run"
  /** Runs after AI Prompt execution. */
  | "after_ai_run"
  /** Fires when revectorization job begins. */
  | "on_vectorization_start"
  /** Executed periodically according to Cron expression settings. */
  | "cron"
  /** Dynamic Query/Mutation field resolver for GraphQL schema. */
  | "graphql";

export type ScriptType = "webhook" | "custom:module" | "esm:module" | "template" | "ai_action";
export type ScriptVisibility = "private" | "public";

export interface FileMetadata {
  /** The unique name/identifier for the script or webhook */
  name?: string;
  /** File extension (js or ts) */
  extension?: "js" | "ts" | "html" | string;
  /** Target collection if this is a collection-scoped hook */
  target_collection?: CollectionName | null;
  /** The structural module type */
  type?: ScriptType;
  /** Local project path */
  path?: string;
  /** System trigger event */
  trigger_type?: TriggerType;
  /** Whether the script is active and running */
  active?: boolean;
  /** Visibility for multi-tenant inheritance ('public' allows tenants to inherit) */
  visibility?: ScriptVisibility;
}

export interface AuthContext {
  id: number;
  email: string;
  role: string;
  scope: string;
}

export interface RecordHookEvent<T = any> {
  trigger: TriggerType;
  record: {
    id: number | null;
    data: T;
  };
  collection: {
    id: number;
    name: string;
    schema?: any;
  };
  auth: AuthContext | null;
}

export interface VoidHookEvent {
  trigger: TriggerType;
  data: any;
  auth: AuthContext | null;
  timestamp: string;
}

export interface GraphqlConfig {
  parent: "Query" | "Mutation" | "User" | "_AuthUser" | string;
  name: string;
  args?: Record<string, string>;
  returnType: string;
}

declare global {
  /** Injected file metadata configuration */
  const __fileMetadata__: FileMetadata;

  /** ApexKit Database Client */
  const $db: {
    records: {
      list<T extends keyof Collections>(
        collection: T, 
        options?: { 
          page?: number; 
          per_page?: number; 
          limit?: number; 
          offset?: number; 
          sort?: string; 
          filter?: string | Record<string, any>; 
          expand?: string; 
          fields?: string; 
        }
      ): Promise<{ items: { id: number; data: Collections[T]; created: string; updated: string; expand?: any }[]; total: number }>;

      get<T extends keyof Collections>(
        collection: T, 
        id: number, 
        expand?: string
      ): Promise<{ id: number; data: Collections[T]; created: string; updated: string; expand?: any } | null>;

      create<T extends keyof Collections>(
        collection: T, 
        data: Partial<Collections[T]>
      ): Promise<{ id: number }>;

      update<T extends keyof Collections>(
        collection: T, 
        id: number, 
        data: Partial<Collections[T]>
      ): Promise<{ id: number; data: Collections[T]; created: string; updated: string }>;

      delete(collection: string, id: number): Promise<boolean>;

      searchVector<T extends keyof Collections>(
        collection: T, 
        field: string, 
        vector: number[], 
        limit?: number
      ): Promise<{ id: number; data: Collections[T]; _score: number }[]>;

      getVector(collection: string, id: number): Promise<{ field_name: string; vector: number[]; model: string }[]>;

      instantSearch(collection: string, query: string, limit?: number): Promise<{ id: number; score: number; snippet: any }[]>;
    };

    query(queryObject: {
      from: string;
      select?: any[];
      where?: Record<string, any>;
      group_by?: string[];
      sort?: string;
      limit?: number;
      offset?: number;
      system?: boolean;
      pipeline?: any[];
    }): Promise<any[]>;

    users: {
      create(email: string, passwordHash: string, role: string, metadata?: Record<string, any>): Promise<{ id: number; email: string; role: string }>;
      get(email: string): Promise<{ id: number; email: string; role: string; metadata?: any } | null>;
    };

    collections: {
      list(): Promise<{ id: number; name: string; schema?: any; index?: string }[]>;
    };

    files: {
      list(limit?: number, offset?: number): Promise<{ id: number; filename: string; original_name: string; mime_type: string; size: number; created_at: string }[]>;
    };
  };

  /** Root Multitenancy and Administrative Manager (Only available in Root context) */
  const $root: {
    db: typeof $db;
    createTenant(id: string, config?: { name?: string; tier?: string; owner_id?: number }): Promise<boolean>;
    updateTenant(id: string, updates: { name?: string; status?: string; tier?: string; max_storage_mb?: number; max_vectors?: number; max_ai_requests?: number }): Promise<boolean>;
    deleteTenant(id: string): Promise<boolean>;
    getTenantDiskUsage(id: string): Promise<number>;
    listTenants(): Promise<any[]>;
    createSandbox(id: string, config?: { name?: string; clone_strategy?: "none" | "schema" | "partial" | "full"; clone_record_limit?: number; collections?: string[]; scripts?: string[]; templates?: string[] }): Promise<boolean>;
    updateSandbox(id: string, updates: { name?: string; status?: string; expires_at?: string }): Promise<boolean>;
    deleteSandbox(id: string): Promise<boolean>;
    getSandboxDiskUsage(id: string): Promise<number>;
    createKey(name: string, config?: { tenant_id?: string; issuer?: string; env_type?: "sys" | "tnnt" | "sk" | "pk"; roles?: string[]; bypass_cors?: boolean }): Promise<{ key: string; info: any }>;
    updateKey(id: number, updates: { name?: string; status?: string; roles?: string[]; bypass_cors?: boolean }): Promise<boolean>;
    deleteKey(id: number): Promise<boolean>;
    listKeys(): Promise<any[]>;
  } | null;

  /** Universal HTTP Client */
  const $http: {
    get(url: string): Promise<string>;
    post(url: string, body: any): Promise<string>;
  };

  /** Native Storage & File Engine */
  const $files: {
    read(filename: string): Promise<string>;
    save(filename: string, data: string | ArrayBuffer | Uint8Array, mime?: string): Promise<{ id: number; url: string; filename: string }>;
    getSignedUrl(filename: string, ttl_secs?: number): Promise<string>;
    registerMetadata(filename: string, options: { originalName?: string; mimeType?: string; size?: number }): Promise<{ id: number; filename: string; url: string; size: number }>;
  };

  /** Scoped Virtual File System */
  const $fs: {
    read(path: string): Promise<string>;
    write(path: string, content: string): Promise<boolean>;
    delete(path: string): Promise<boolean>;
    list(path: string): Promise<{ name: string; isDir: boolean; size: number }[]>;
    exists(path: string): Promise<boolean>;
    mkdir(path: string): Promise<boolean>;
    stat(path: string): Promise<{ size: number; isDir: boolean; created?: number; modified?: number }>;
  };

  /** Fast In-Memory Zip Creator & Extractor */
  const $zip: {
    create(files: Record<string, string | Uint8Array>): string;
    extract(base64Zip: string): Record<string, string>;
    inspect(base64Zip: string): { total_size: number; file_count: number; files: any[] };
  };

  /** Local AI Embeddings Engine */
  const $ai: {
    embed(text: string): Promise<number[]>;
    meanVector(vectors: number[][]): number[];
    cosineSimilarity(v1: number[], v2: number[]): number;
  };

  /** In-Memory & Tenant-Isolated Fast Cache */
  const $cache: {
    get(key: string): Promise<string | null>;
    set(key: string, value: any, ttl_secs?: number): Promise<void>;
    delete(key: string): Promise<void>;
    del(key: string): Promise<void>;
    incr(key: string, delta?: number): Promise<number>;
    listKeys(): Promise<string[]>;
  };

  /** Background Queue Orchestration System (60s CPU Budget every 5 Minutes) */
  const $queue: {
    /**
     * Spawns an asynchronous background process orchestrated in JavaScript.
     * @param fnOrCode - The function or module code to execute in background
     * @param options - Execution options (timeout defaults to 60000ms)
     */
    spawn<T = any>(
      fnOrCode: ((pid: string, req: Request) => Promise<T> | T) | string,
      options?: { timeoutMs?: number; args?: any }
    ): Promise<{ pid: string; status: "queued" | "running" }>;

    /**
     * Queries the active execution status of a spawned queue job.
     * @param pid - Job ID
     */
    status(pid: string): Promise<{
      pid: string;
      status: "queued" | "running" | "completed" | "failed" | "timed_out" | "not_found";
      runtime_ms: number;
      error?: string;
    }>;

    /**
     * Retrieves the final result or error of a completed queue job.
     * @param pid - Job ID
     */
    result<T = any>(pid: string): Promise<{
      pid: string;
      status: "queued" | "running" | "completed" | "failed" | "timed_out" | "not_found";
      runtime_ms: number;
      result?: T;
      error?: string;
    }>;
  };

  /** Subprocess Runner (Root scope only) */
  const $cmd: {
    run(program: string, args?: string[], options?: { cwd?: string; env?: Record<string, string>; timeout?: number }): Promise<{ stdout: string; stderr: string; status: number }>;
    spawn(program: string, args?: string[], options?: { cwd?: string; env?: Record<string, string>; timeout?: number; onProgress?: { regex?: string; channel?: string; event?: string } }): Promise<{ pid: number; status: string }>;
    status(pid: number): Promise<any>;
    setLimit(program: string, limit: number): Promise<any>;
    kill(pid: number): Promise<any>;
  };

  /** Outbound SMTP Email Dispatcher */
  const $mail: {
    send(to: string, subject: string, body: string): Promise<boolean>;
  };

  /** Real-time WebSocket & SSE Event Dispatcher */
  const $realtime: {
    send(channel: string, event: string, data: any): Promise<boolean>;
  };

  /** Script Inter-calling Engine */
  const $run: {
    script(name: string, payload: any): Promise<any>;
  };

  /** WebAssembly Raw Loader & WASI Runner */
  const $wasm: {
    call(
      wasmBase64OrName: string,
      funcName: string,
      args: number[],
      options?: { name?: string; memoryMb?: number; timeoutMs?: number }
    ): Promise<number | number[]>;
    runWasi(
      wasmBase64OrName: string,
      cliArgs?: string[],
      options?: { name?: string; memoryMb?: number; timeoutMs?: number }
    ): Promise<boolean>;
  };

  /** Cryptographic & String Utilities */
  const $util: {
    uuid(): string;
    slugify(text: string): string;
    hash(text: string, alg: "sha256" | "sha512"): string;
    hmac(text: string, key: string): string;
    base64Encode(data: string | ArrayBuffer | Uint8Array): string;
    base64EncodeBuffer(buffer: ArrayBuffer | Uint8Array): string;
    base64Decode(text: string): string;
    base64DecodeBuffer(text: string): ArrayBuffer;
    sleep(ms: number): Promise<void>;
    randomHex(len?: number): string;
  };

  /** Environment & Configuration Secrets Accessor */
  const $env: {
    get(key: string): Promise<string>;
    readonly APP_URL: string;
    readonly SMTP_BLOCKED: boolean;
  };

  /** Full Fetch API support */
  function fetch(input: string | Request | URL, init?: { method?: string; headers?: any; body?: any; redirect?: "follow" | "manual" | "error" }): Promise<Response>;

  /** Full WebAssembly standard namespace */
  const WebAssembly: {
    Memory: new (init: { initial: number; maximum?: number }) => { buffer: ArrayBuffer };
    Instance: new (module: any, imports?: any) => { exports: Record<string, any> };
    Module: new (bytes: ArrayBuffer | Uint8Array | string) => any;
    instantiate(bufferSource: ArrayBuffer | Uint8Array | string, importObject?: any): Promise<{ module: any; instance: { exports: Record<string, any> } } | { exports: Record<string, any> }>;
    instantiateStreaming(source: Response | Promise<Response>, importObject?: any): Promise<{ module: any; instance: { exports: Record<string, any> } }>;
    compile(bufferSource: ArrayBuffer | Uint8Array | string): Promise<any>;
  };

  class Headers {
    constructor(init?: Record<string, string> | [string, string][] | Headers);
    get(name: string): string | null;
    set(name: string, value: string): void;
    has(name: string): boolean;
    delete(name: string): void;
    forEach(callback: (value: string, key: string) => void): void;
  }

  class Response {
    constructor(body?: any, init?: { status?: number; statusText?: string; headers?: Record<string, string> | Headers });
    readonly status: number;
    readonly statusText: string;
    readonly ok: boolean;
    readonly headers: Headers;
    readonly url: string;
    json(): Promise<any>;
    text(): Promise<string>;
    arrayBuffer(): Promise<ArrayBuffer>;
  }

  class Request {
    constructor(input: string | { url: string; method?: string; headers?: any; bodyData?: any }, init?: { method?: string; headers?: any; body?: any });
    readonly method: string;
    readonly url: string;
    readonly headers: Headers;
    readonly auth: AuthContext | null;
    readonly args: any;
    json(): Promise<any>;
    text(): Promise<string>;
    arrayBuffer(): Promise<ArrayBuffer>;
    clone(): Request;
  }

  class URL {
    constructor(urlStr: string, baseStr?: string);
    readonly href: string;
    readonly protocol: string;
    readonly host: string;
    readonly hostname: string;
    readonly port: string;
    readonly origin: string;
    readonly pathname: string;
    readonly search: string;
    readonly hash: string;
    readonly searchParams: {
      get(key: string): string | null;
      has(key: string): boolean;
      getAll(key: string): string[];
    };
    toString(): string;
  }
}
export {};