/**
 * ApexKit Global Types & IntelliSense
 * Auto-generated by apexkit-watch.js
 */

export interface Collections {
  "profiles": {
    metadata?: Record<string, any> | any[];
    user_id: number | string;
  };
  "drive_items": {
    preview?: Record<string, any> | any[];
    file?: string;
    metadata?: Record<string, any> | any[];
    configurations?: Record<string, any> | any[];
    physical_file?: string;
    is_file?: boolean;
    path: string;
    added_by: (number | string)[];
  };
  "drive_shares": {
    item_id?: number;
    expires_at?: string;
    token: string;
    access_level: string;
    password_hash?: string;
    folder_path?: string;
  };
}

export type CollectionName = "profiles" | "drive_items" | "drive_shares";

export interface CollectionExpands {
  "profiles": {
    [reverse_relation: string]: any;
  };
  "drive_items": {
    added_by?: Array<{ id: number | string; data: Collections["1"]; created: string; updated: string; expand?: any }>;
    [reverse_relation: string]: any;
  };
  "drive_shares": {
    [reverse_relation: string]: any;
  };
}



export type TriggerType =
  /** Triggered via HTTP GET/POST/PUT/DELETE on /api/v1/run/:name */
  | "manual"
  /** Runs before a record is inserted. Can validate or mutate data. */
  | "before_create_record"
  /** Runs after a record is inserted. Used for notifications/indexes. */
  | "after_create_record"
  /** Runs before an existing record is updated. Can validate changes. */
  | "before_update_record"
  /** Runs after a record is updated. */
  | "after_update_record"
  /** Runs before a record is deleted. Can block deletion. */
  | "before_delete_record"
  /** Runs after a record has been deleted. */
  | "after_delete_record"
  /** Intercepts list queries before they execute. */
  | "before_list_records"
  /** Filters or transforms listed records before response. */
  | "after_list_records"
  /** Runs before a single record is fetched. */
  | "before_get_record"
  /** Transforms a fetched record before response. */
  | "after_get_record"
  /** Runs before user authentication. Can verify IP/Rate limits. */
  | "before_user_login"
  /** Runs after successful user login. */
  | "after_user_login"
  /** Runs before user registration. Enforce roles or rules. */
  | "before_user_create"
  /** Runs after user registration. Trigger welcome emails. */
  | "after_user_create"
  /** Runs before a user is deleted. */
  | "before_user_delete"
  /** Runs after a user is deleted. */
  | "after_user_delete"
  /** Intercepts user list queries. */
  | "before_list_users"
  /** Transforms user list responses. */
  | "after_list_users"
  /** Validates collection schema before creation. */
  | "before_collection_create"
  /** Runs after collection creation. */
  | "after_collection_create"
  /** Runs before collection schema updates. */
  | "before_collection_update"
  /** Runs after collection schema updates. */
  | "after_collection_update"
  /** Runs before collection deletion. */
  | "before_collection_delete"
  /** Runs before a file is written to storage. */
  | "before_file_upload"
  /** Runs after file upload. Can trigger virus scan or indexing. */
  | "after_file_upload"
  /** Runs before file is deleted. */
  | "before_file_delete"
  /** Runs after file is deleted. */
  | "after_file_delete"
  /** Runs before relationship is linked. */
  | "before_relation_create"
  /** Runs after relationship is linked. */
  | "after_relation_create"
  /** Runs before relationship is removed. */
  | "before_relation_delete"
  /** Runs after relationship is removed. */
  | "after_relation_delete"
  /** Runs before a tenant database is provisioned. */
  | "before_tenant_create"
  /** Runs after tenant database is provisioned. */
  | "after_tenant_create"
  /** Intercepts all incoming HTTP requests to a tenant. */
  | "before_tenant_request"
  /** Processes tenant HTTP response metrics. */
  | "after_tenant_request"
  /** Intercepts sandbox requests. */
  | "before_sandbox_request"
  /** Processes sandbox response metrics. */
  | "after_sandbox_request"
  /** Intercepts AI Prompt Actions to inject RAG search vectors. */
  | "before_ai_run"
  /** Runs after AI Prompt execution. */
  | "after_ai_run"
  /** Fires when revectorization job begins. */
  | "on_vectorization_start"
  /** Executed periodically according to Cron expression settings. */
  | "cron"
  /** Dynamic Query/Mutation field resolver for GraphQL schema. */
  | "graphql";

export type ScriptType = "webhook" | "custom:module" | "esm:module" | "template" | "ai_action";
export type ScriptVisibility = "private" | "public";

export interface FileMetadata {
  name?: string;
  extension?: "js" | "ts" | "html" | string;
  target_collection?: CollectionName | null;
  type?: ScriptType;
  path?: string;
  trigger_type?: TriggerType;
  active?: boolean;
  visibility?: ScriptVisibility;
}

export interface AuthContext {
  id: number | string;
  email: string;
  role: string;
  scope: string;
}

export interface RecordItem<T extends keyof Collections> {
  id: number | string;
  data: Collections[T];
  created: string;
  updated: string;
  expand?: CollectionExpands[T];
}

export interface RecordHookEvent<T extends keyof Collections = any> {
  trigger: TriggerType;
  record: {
    id: number | string | null;
    data: T extends keyof Collections ? Collections[T] : any;
  };
  collection: {
    id: number;
    name: string;
    schema?: any;
  };
  auth: AuthContext | null;
}

export interface VoidHookEvent {
  trigger: TriggerType;
  data: any;
  auth: AuthContext | null;
  timestamp: string;
}

export interface GraphqlConfig {
  parent: "Query" | "Mutation" | "User" | "_AuthUser" | string;
  name: string;
  args?: Record<string, string>;
  returnType: string;
}

declare global {
  const __fileMetadata__: FileMetadata;

  /** ApexKit Database Client */
  const $db: {
    records: {
      list<T extends keyof Collections>(
        collection: T, 
        options?: { 
          page?: number; 
          per_page?: number; 
          limit?: number; 
          offset?: number; 
          sort?: string; 
          filter?: string | Record<string, any>; 
          expand?: string; 
          fields?: string; 
        }
      ): Promise<{ items: RecordItem<T>[]; total: number }>;

      get<T extends keyof Collections>(
        collection: T, 
        id: number | string, 
        expand?: string
      ): Promise<RecordItem<T> | null>;

      create<T extends keyof Collections>(
        collection: T, 
        data: Partial<Collections[T]>
      ): Promise<{ id: number | string }>;

      update<T extends keyof Collections>(
        collection: T, 
        id: number | string, 
        data: Partial<Collections[T]>
      ): Promise<RecordItem<T>>;

      delete(collection: string, id: number | string): Promise<boolean>;

      searchVector<T extends keyof Collections>(
        collection: T, 
        field: string, 
        vector: number[], 
        limit?: number
      ): Promise<(RecordItem<T> & { _score: number })[]>;

      getVector(collection: string, id: number | string): Promise<{ field_name: string; vector: number[]; model: string }[]>;

      instantSearch(collection: string, query: string, limit?: number): Promise<{ id: number | string; score: number; snippet: any }[]>;
    };

    query(queryObject: {
      from: string;
      select?: any[];
      where?: Record<string, any>;
      group_by?: string[];
      sort?: string;
      limit?: number;
      offset?: number;
      system?: boolean;
      pipeline?: any[];
    }): Promise<any[]>;

    users: {
      create(email: string, passwordHash: string, role: string, metadata?: Record<string, any>): Promise<{ id: number | string; email: string; role: string }>;
      get(email: string): Promise<{ id: number | string; email: string; role: string; metadata?: any } | null>;
    };

    collections: {
      list(): Promise<{ id: number; name: string; schema?: any; index?: string }[]>;
    };

    files: {
      list(limit?: number, offset?: number): Promise<{ id: number | string; filename: string; original_name: string; mime_type: string; size: number; created_at: string }[]>;
    };
  };

  /** Root Multitenancy and Administrative Manager (Only available in Root context) */
  const $root: {
    db: typeof $db;
    createTenant(id: string, config?: { name?: string; tier?: string; owner_id?: number }): Promise<boolean>;
    updateTenant(id: string, updates: { name?: string; status?: string; tier?: string; max_storage_mb?: number; max_vectors?: number; max_ai_requests?: number }): Promise<boolean>;
    deleteTenant(id: string): Promise<boolean>;
    getTenantDiskUsage(id: string): Promise<number>;
    listTenants(): Promise<any[]>;
    createSandbox(id: string, config?: { name?: string; clone_strategy?: "none" | "schema" | "partial" | "full"; clone_record_limit?: number; collections?: string[]; scripts?: string[]; templates?: string[] }): Promise<boolean>;
    updateSandbox(id: string, updates: { name?: string; status?: string; expires_at?: string }): Promise<boolean>;
    deleteSandbox(id: string): Promise<boolean>;
    getSandboxDiskUsage(id: string): Promise<number>;
    createKey(name: string, config?: { tenant_id?: string; issuer?: string; env_type?: "sys" | "tnnt" | "sk" | "pk"; roles?: string[]; bypass_cors?: boolean }): Promise<{ key: string; info: any }>;
    updateKey(id: number | string, updates: { name?: string; status?: string; roles?: string[]; bypass_cors?: boolean }): Promise<boolean>;
    deleteKey(id: number | string): Promise<boolean>;
    listKeys(): Promise<any[]>;
  } | null;

  /** Universal HTTP Client */
  const $http: {
    get(url: string): Promise<string>;
    post(url: string, body: any): Promise<string>;
  };

  /** Native Storage & File Engine */
  const $files: {
    read(filename: string): Promise<string>;
    delete(filenameOrId: string | number): Promise<boolean>;
    save(filename: string, data: string | ArrayBuffer | Uint8Array, mime?: string): Promise<{ id: number | string; url: string; filename: string }>;
    getSignedUrl(filename: string, ttl_secs?: number): Promise<string>;
  };

  /** Scoped Virtual File System */
  const $fs: {
    read(path: string): Promise<string>;
    write(path: string, content: string): Promise<boolean>;
    delete(path: string): Promise<boolean>;
    list(path: string): Promise<{ name: string; isDir: boolean; size: number }[]>;
    exists(path: string): Promise<boolean>;
    mkdir(path: string): Promise<boolean>;
    stat(path: string): Promise<{ size: number; isDir: boolean; created?: number; modified?: number }>;
  };

  /** Fast In-Memory Zip Creator & Extractor */
  const $zip: {
    create(files: Record<string, string | Uint8Array>): string;
    extract(base64Zip: string): Record<string, string>;
    inspect(base64Zip: string): { total_size: number; file_count: number; files: any[] };
  };

  /** Local AI Embeddings Engine */
  const $ai: {
    embed(text: string): Promise<number[]>;
    meanVector(vectors: number[][]): number[];
    cosineSimilarity(v1: number[], v2: number[]): number;
  };

  /** In-Memory & Tenant-Isolated Fast Cache */
  const $cache: {
    get(key: string): Promise<string | null>;
    set(key: string, value: any, ttl_secs?: number): Promise<void>;
    delete(key: string): Promise<void>;
    del(key: string): Promise<void>;
    incr(key: string, delta?: number): Promise<number>;
    listKeys(): Promise<string[]>;
  };

  /** Background Queue Orchestration System */
  const $queue: {
    spawn<T = any>(
      fnOrCode: ((pid: string, req: Request) => Promise<T> | T) | string,
      options?: { timeoutMs?: number; args?: any }
    ): Promise<{ pid: string; status: "queued" | "running" }>;
    status(pid: string): Promise<{
      pid: string;
      status: "queued" | "running" | "completed" | "failed" | "timed_out" | "not_found";
      runtime_ms: number;
      error?: string;
    }>;
    result<T = any>(pid: string): Promise<{
      pid: string;
      status: "queued" | "running" | "completed" | "failed" | "timed_out" | "not_found";
      runtime_ms: number;
      result?: T;
      error?: string;
    }>;
  };

  /** Subprocess Runner (Root scope only) */
  const $cmd: {
    run(program: string, args?: string[], options?: { cwd?: string; env?: Record<string, string>; timeout?: number }): Promise<{ stdout: string; stderr: string; status: number }>;
    spawn(program: string, args?: string[], options?: { cwd?: string; env?: Record<string, string>; timeout?: number; onProgress?: { regex?: string; channel?: string; event?: string } }): Promise<{ pid: number; status: string }>;
    status(pid: number): Promise<any>;
    setLimit(program: string, limit: number): Promise<any>;
    kill(pid: number): Promise<any>;
  };

  /** Outbound SMTP Email Dispatcher */
  const $mail: {
    send(to: string, subject: string, body: string): Promise<boolean>;
  };

  /** Real-time WebSocket & SSE Event Dispatcher */
  const $realtime: {
    send(channel: string, event: string, data: any): Promise<boolean>;
  };

  /** Script Inter-calling Engine */
  const $run: {
    script(name: string, payload: any): Promise<any>;
  };

  /** WebAssembly Raw Loader & WASI Runner */
  const $wasm: {
    call(
      wasmBase64OrName: string,
      funcName: string,
      args: number[],
      options?: { name?: string; memoryMb?: number; timeoutMs?: number }
    ): Promise<number | number[]>;
    runWasi(
      wasmBase64OrName: string,
      cliArgs?: string[],
      options?: { name?: string; memoryMb?: number; timeoutMs?: number }
    ): Promise<boolean>;
  };

  /** Cryptographic & String Utilities */
  const $util: {
    uuid(): string;
    slugify(text: string): string;
    hash(text: string, alg: "sha256" | "sha512"): string;
    hmac(text: string, key: string): string;
    base64Encode(data: string | ArrayBuffer | Uint8Array): string;
    base64EncodeBuffer(buffer: ArrayBuffer | Uint8Array): string;
    base64Decode(text: string): string;
    base64DecodeBuffer(text: string): ArrayBuffer;
    sleep(ms: number): Promise<void>;
    randomHex(len?: number): string;
  };

  /** Environment & Configuration Secrets Accessor */
  const $env: {
    get(key: string): Promise<string>;
    readonly APP_URL: string;
    readonly SMTP_BLOCKED: boolean;
  };

  function fetch(input: string | Request | URL, init?: { method?: string; headers?: any; body?: any; redirect?: "follow" | "manual" | "error" }): Promise<Response>;

  class Headers {
    constructor(init?: Record<string, string> | [string, string][] | Headers);
    get(name: string): string | null;
    set(name: string, value: string): void;
    has(name: string): boolean;
    delete(name: string): void;
    forEach(callback: (value: string, key: string) => void): void;
  }

  class Response {
    constructor(body?: any, init?: { status?: number; statusText?: string; headers?: Record<string, string> | Headers });
    readonly status: number;
    readonly statusText: string;
    readonly ok: boolean;
    readonly headers: Headers;
    readonly url: string;
    json(): Promise<any>;
    text(): Promise<string>;
    arrayBuffer(): Promise<ArrayBuffer>;
  }

  class Request {
    constructor(input: string | { url: string; method?: string; headers?: any; bodyData?: any }, init?: { method?: string; headers?: any; body?: any });
    readonly method: string;
    readonly url: string;
    readonly headers: Headers;
    readonly auth: AuthContext | null;
    readonly args: any;
    json(): Promise<any>;
    text(): Promise<string>;
    arrayBuffer(): Promise<ArrayBuffer>;
    clone(): Request;
  }
}
export {};